### ISSUE TITLE
Reduce log spam

### ISSUE THREAD

**Issue by Newtoniano** [sleeyax/voltra#15]
**Describe the feature you'd like**
With the current logging implementation, there is a bit too much unnecessary spam while running the bot in production, even with the log level set to `INFO`.

**Describe alternatives you've considered**
Consider downgrading many of the current `INFO` logs to `DEBUG` instead. 
In my opinion, the bot should only use the `INFO` level for important information, like the pairs that reached the volatility threshold, buy and sell events and the relative info (pct change, pnl etc). All the constant API polling logs (both before opening positions and while positions are open) can be moved to `DEBUG` instead, so that it's clearer to follow what the bot is actually trading.

I'd like to hear your thoughts and feedback on this.

**Comment by sleeyax** [comment]
Agreed, sounds like a better approach. There's not much thought put into logging so far besides for  development purposes so I totally agree we should indeed move most info messages to debug instead.
